### ISSUE TITLE
v3.2.0 Feature: Add Stripe subscription model to Taboo AI

### ISSUE THREAD

**Issue by xmliszt** [xmliszt/taboo-ai#223]
## ToDos

- [x] Set up Stripe account
- [x] Firebase db model setup with token count for user
- [x] PRO plan subscribe flow
- [x] Downgrade to FREE plan flow ( == Cancel subscription)
- [x] Cancel free trial?
- [x] User delete account will cancel subscriptions as well, but keep customerId (prevent exploit on free trial), reset customerPlanType to 'free'
- [x] Robust Testing
- [x] Better access to Pricing Page
- [x] User can manage the subscription
- [x] Update subscription plan features: FREE: only the latest 1 game result in profile for viewing (Different UI design). PRO: the latest 10 game results in profile for viewing.

## Resources:

- https://vercel.com/guides/getting-started-with-nextjs-typescript-stripe
- https://medium.com/@drtechpunk/how-to-set-up-stripe-subscriptions-for-nextjs-13-with-the-app-directory-e36f1df204db

## House keeping
- [x] Add firebase cloud functions deployment to the pipeline
- [x] Update Stripe product description for actual 

## Next Steps - Handle PRO feature flag
- [x] Profile > Latest 1 | 10 game results to display
- [x] AI Mode
